### ISSUE TITLE
نمایش پیغام خطایی رخ داده است در پنل جنگو

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#103]
بعد از ذخیره تغییرات در پنل جنگو صفحه خطایی رخ داده است نمایش داده می شود در حالی که تغییرات ذخیره شده اند
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
برای چه تغییراتی و برای کدام مدل ؟ 

@sahar-shafiee

**Comment by sahar-shafiee** [comment]
> برای چه تغییراتی و برای کدام مدل ؟
> 
> @sahar-shafiee

بچه های عملیات میگن هر تغییری که ایجاد میکنند شامل تغییر در محصول ، تغییر در کوپن
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
![image](https://user-images.githubusercontent.com/54346362/169976272-5fe79e81-fab4-4c4a-980e-f28181c24a42.png)


This error happens when the app and database are not synced for PK for creating a new instanst.
The reason for this is that there is a change in the database(like importing).
I have previously reported this problem with the storage of transactions. @likecodingloveproblems 


I found these solutions: 

1. https://www.codegrepper.com/code-examples/whatever/django+ERROR%3A++duplicate+key+value+violates+unique+constraint+++Key+%28email%29%3D%28%29+already+exists.

2. https://medium.com/odds-team/fix-django-migration-pkey-errors-16aa213e10b

**Comment by PouryaMansouri** [comment]
![image](https://user-images.githubusercontent.com/54346362/169978475-1457f171-96fb-4bea-8bbf-588a76604cb3.png)


We still have this error in the transaction model. @likecodingloveproblems

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee it seems, it's done for coupon, please let operation team test it.

**Comment by PouryaMansouri** [comment]
> > ![image](https://user-images.githubusercontent.com/54346362/169978475-1457f171-96fb-4bea-8bbf-588a76604cb3.png)
> > We still have this error in the transaction model. @likecodingloveproblems
> 
> I check it, it's not the case here, sequence and id are sync @PouryaMansouri

You can't see this error in local, the production app and production database are not synce.

**Comment by likecodingloveproblems** [comment]
this error can't be created in the development phase because we need to have a valid IP to connect to bank gateway!

what do you mean about _the production app and production database aren't sync_?

**Comment by PouryaMansouri** [comment]
> this error can't be created in the development phase because we need to have a valid IP to connect to bank gateway!
> 
> what do you mean about _the production app and production database aren't sync_?

For example:
in this error: 


> > ![image](https://user-images.githubusercontent.com/54346362/169978475-1457f171-96fb-4bea-8bbf-588a76604cb3.png)


the app wants to create a new instance of "payoff_transancrion", your app wants to create it with the next id that it remembers from the last instance it made, the id is 2752, but this id was created before and your app didn't know,

**Comment by likecodingloveproblems** [comment]
we will discuss it in the daily meeting :wink:

**Comment by PouryaMansouri** [comment]
> we will discuss it in the daily meeting wink

We will discuss this issue tomorrow in the meeting.

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri why do you reopen?
