### ISSUE TITLE
باگ فعال شدن حجره های غیرفعال

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#74]
بعضی از حجره هایی که از قدیم غیرفعال بودند به طور خودکار فعال شدند و ثبت سفارش خوردند(لطفا بررسی شود.)
مثال :حجره برنج قنات آبشار،چرم علی آبادی 

@likecodingloveproblems

**Comment by likecodingloveproblems** [comment]
I check this shop and its Publish and Available properties are True!

- One scenario is changing this value from the admin panel, two of the Operation team members have superuser access.(Mahdavi and torkzadeh mahani).

Is there any other place that the user can change this properties?

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee 
@PouryaMansouri

**Comment by likecodingloveproblems** [comment]
I want to create an issue to clean admin panel authority and functionality for the operation team and financial team.
So I think we must explore use cases.
I think with the help of @saman7799 and @MaryamSamareh we can extract use cases and @PouryaMansouri can give you a robust mind about admin panel functionality and power.

**Comment by likecodingloveproblems** [comment]
We can't find the root cause of this problem, So I have some assumption

1. there are some places the user by themselves can change shop status! we must check it in the app @MaryamSamareh please check this.
2. By panel admin **Omid** or **Seyed** changed shop status. because they have superuser privileges. @saman7799 please ask from Omid, and then we need to extract operation team use cases to limit their access in the admin panel
3. we need an architecture to save all events. @likecodingloveproblems please don't dream it so huge, have a plan to take it to the reallity

**Comment by saman7799** [comment]
@likecodingloveproblems 
با آقا امید صحبت کردم گفتن اصلا حجره ای در این مدت زمان فعال نکرده اند فقط چند حجره با هماهنگی تیم فنی غیرفعال شده است.

**Comment by likecodingloveproblems** [comment]
there are some places the user by themselves can change shop status! we must check it in the app @MaryamSamareh please check this.
@MaryamSamareh

**Comment by likecodingloveproblems** [comment]
این ایشو بسته میشه چون نمیشه دلیل اصلی این مساله رو پیدا کرد.
